name: Go Build (Compile Only)

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'README*'
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'README*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Compile root project (build only)
        run: |
          echo "Building root modules"
          go vet ./...
          go build ./...

      - name: Setup Node (for CDK)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk@2

      - name: CDK synth demo-infra projects
        run: |
          echo "Synthesizing demo-infra stacks"
          for dir in demo-infra/*/; do
            if [ -f "$dir/cdk.json" ]; then
              echo "cdk synth in $dir"
              cd "$dir"
              # go mod tidy & build to ensure jsii compile step passes
              if [ -f "go.mod" ]; then
                go vet ./...
                go build ./...
              fi
              # synth (offline)
              cdk synth --all --no-lookups
              cd - > /dev/null
            fi
          done 