name: Go Build (Compile Only)

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'README*'
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'README*'

permissions:
  contents: read

jobs:
  build-root:
    name: Build Root Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Compile root project (build only)
        run: |
          echo "Building root modules"
          go vet ./...
          go build ./...

  discover-cdk-projects:
    name: Discover CDK Projects
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Discover CDK projects
        id: set-matrix
        run: |
          echo "Scanning for CDK projects in demo-infra/"

          projects=$(find demo-infra -name "cdk.json" -type f | \
          sed 's|/cdk.json||' | \
          sed 's|demo-infra/||' | \
          jq -R -s -c 'split("\n")[:-1]')
          
          echo "Found projects: $projects"
          echo "matrix={\"project\":$projects}" >> $GITHUB_OUTPUT

  build-cdk:
    name: Build CDK Projects
    runs-on: ubuntu-latest
    needs: discover-cdk-projects
    strategy:
      matrix: ${{ fromJson(needs.discover-cdk-projects.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup Node (for CDK)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk@2

      - name: Build and synth CDK project (${{ matrix.project }})
        run: |
          echo "Building and synthesizing ${{ matrix.project }}"
          cd demo-infra/${{ matrix.project }}
          
          # Go build first
          if [ -f "go.mod" ]; then
            go vet ./...
            go build ./...
          fi
          
          # CDK synth (offline)
          cdk synth --all --no-lookups 